security:
  webauthn:
    rp-id: manada-solidaria.com
    allowed-origins: https://manadasolidaria.com
  cors:
    allowed-origins: http://manadasolidaria.com, https://manadasolidaria.com
    allowed-credentials: true
