security:
  webauthn:
    rp-id: dev.manadasolidaria.com
    allowed-origins: https://dev.manadasolidaria.com
  cors:
    allowed-origins: https://dev.manadasolidaria.com, http://localhost:5173
    allowed-origin-patterns: http://192.168.*.*:5173
    allowed-credentials: true
