name: Local
variables:
  - name: MANADA_SOLIDARIA_HOST
    value: localhost:8080
  - name: access_token
    value: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNzFlYTlkOS1kMDdlLTQzZWYtYjNhOS0xYjA0MDFhYWZjZmQiLCJleHAiOjE3ODkxNzQ4OTEsImlhdCI6MTc4OTE3MTI5MSwicm9sZXMiOlsiQ09NTVVOSVRZIl19.yJClUR0HybIS7VPp3L1PdmO-Q8sLGVir3OS3shmKEqM
  - name: refresh_token
    value: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNzFlYTlkOS1kMDdlLTQzZWYtYjNhOS0xYjA0MDFhYWZjZmQiLCJleHAiOjE3ODkxNzg0OTEsImlhdCI6MTc4OTE3MTI5MX0.StyG2LPbrfaQqG4BliV2eIk0khRmqAa2qHZEiVs1Xvg
